export const TWEAKS_DEFAULTS = {
  brandName: "Ballard Stays",
  accent: "#2F4A3A",
  accentSoft: "#E8EDE3",
  discountPct: 10,
  fontDisplay: "Fraunces",
  fontBody: "Inter",
  heroStyle: "editorial",
  showSavingsBanner: true,
};

export const PROPERTIES = [
  {
    id: "bamboo",
    name: "Ballard Bamboo Indulgence",
    tagline: "Cozy first-floor suite",
    type: "Private room in townhouse",
    sleeps: 2, bedrooms: 1, beds: 1, baths: 1,
    airbnbRate: 129,
    airbnbUrl: "https://www.airbnb.com/rooms/890746600710694659?guests=1&adults=1&s=67&unique_share_id=02b1924f-57bd-4d8b-9af4-530b172472b9",
    rating: 4.96, reviews: 163, guestFavorite: true,
    heroPlaceholder: "First-floor bedroom with bamboo accent wall",
    heroImage: "/img/bamboo/01-bedroom-hero.jpg",
    shortDesc: "A bright, stylish bedroom with dedicated bathroom on the first floor. Ideal for a single traveler or couple who want privacy and an easy home base in Ballard.",
    perfectFor: "Couples · Solo travelers · Short business trips",
    longDesc: "Stylish, cozy room on the first floor of a new-construction townhouse. Room-darkening shades, extra bedding, dedicated workspace, and a private bath. Steps from Ballard's best coffee, restaurants, and breweries. Free & safe street parking. Walk to Bus 28 & RapidRide D for a 15 minute ride to downtown Seattle.",
    photos: [
      { src: "/img/bamboo/01-bedroom-hero.jpg", label: "The queen bedroom, bathed in afternoon light" },
      { src: "/img/bamboo/02-bedroom-queen.jpg", label: "Queen bed with bamboo headboard" },
      { src: "/img/bamboo/03-nightstand-art.jpg", label: "Nightstand detail, curated art prints" },
      { src: "/img/bamboo/04-bathroom-full.jpg", label: "Private bathroom with marble tile" },
      { src: "/img/bamboo/05-bathroom-vanity.jpg", label: "Vanity with quartz countertop" },
      { src: "/img/bamboo/06-desk-window.jpg", label: "Dedicated workspace by the window" },
      { src: "/img/bamboo/07-workspace.jpg", label: "Bamboo closet & desk corner" },
      { src: "/img/bamboo/08-townhouse-exterior.jpg", label: "Townhouse entrance, 922B" },
      { src: "/img/bamboo/09-sakura-curtain.jpg", label: "Sakura-themed noren entry" },
      { src: "/img/bamboo/10-closet-desk.jpg", label: "Open closet with plenty of hangers" },
    ],
    amenities: ["Wifi", "Dedicated workspace", "Bathtub", "Free street parking", "Self check-in (keypad)", "Lock on bedroom door", "Mini-fridge", "Microwave", "Kettle", "Room-darkening shades", "Smoke alarm", "CO alarm"],
  },
  {
    id: "gateway",
    name: "Ballard Top Floor Suite with Private Chef Kitchen",
    tagline: "Private suite + chef kitchen + rooftop",
    type: "Private suite in townhouse",
    sleeps: 4, bedrooms: 1, beds: 2, baths: 1,
    airbnbRate: 229,
    airbnbUrl: "https://www.airbnb.com/rooms/1451097135219726178?guests=1&adults=1&s=67&unique_share_id=77b656d7-876e-42ad-bab3-dafd01f089ad",
    rating: 5.0, reviews: 3, guestFavorite: true,
    heroPlaceholder: "3rd-floor master bedroom with sakura tree view",
    heroImage: "/img/topfloor/01.jpg",
    shortDesc: "Exclusive access to the 2nd-floor kitchen & living, 3rd-floor master suite, and the rooftop deck with Olympic views. A full home-feel at a smart price.",
    perfectFor: "Couples · Small families · Remote workers",
    longDesc: "Private home-like stay across three floors of a modern Ballard townhouse. Exclusive access to 2nd-floor living & full chef kitchen, 3rd-floor master suite with ensuite double-sink bath, height-adjustable workstation, and the rooftop deck with Olympic Mountain views. A/C in bedroom and living room.",
    photos: [
      { src: "/img/topfloor/01.jpg", label: "Master bedroom" },
      { src: "/img/topfloor/02.jpg", label: "Second bedroom" },
      { src: "/img/topfloor/03.jpg", label: "Third bedroom" },
      { src: "/img/topfloor/04.jpg", label: "Rooftop deck" },
      { src: "/img/topfloor/05.jpg", label: "Rooftop deck view" },
      { src: "/img/topfloor/06.jpg", label: "Rooftop deck, sunset" },
      { src: "/img/topfloor/07.jpg", label: "Rooftop deck, Olympic Mountain view" },
      { src: "/img/topfloor/08.jpg", label: "Rooftop deck, seating" },
      { src: "/img/topfloor/09.jpg", label: "Rooftop deck, detail" },
      { src: "/img/topfloor/10.jpg", label: "Dining area" },
      { src: "/img/topfloor/11.jpg", label: "Townhouse front" },
      { src: "/img/topfloor/12.jpg", label: "Chef kitchen" },
      { src: "/img/topfloor/13.png", label: "Living room with sofa bed" },
      { src: "/img/topfloor/14.png", label: "Living room, second view" },
      { src: "/img/topfloor/15.jpg", label: "Outside entrance" },
      { src: "/img/topfloor/16.jpg", label: "Bathroom" },
      { src: "/img/topfloor/17.jpg", label: "Second bathroom" },
      { src: "/img/topfloor/18.jpg", label: "Washer/Dryer" },
    ],
    amenities: ["Full chef kitchen", "Wifi", "Dedicated workspace", "TV", "A/C (bedroom + living)", "Rooftop deck", "Olympic Mountain views", "Self check-in (keypad)", "Lock on bedroom door", "Washer/Dryer", "Cookware", "Coffee maker"],
  },
  {
    id: "zen",
    name: "Sunlit Zen Retreat",
    tagline: "Entire 2BR/2BA townhome, sleeps 6",
    type: "Entire townhouse",
    sleeps: 6, bedrooms: 2, beds: 3, baths: 2,
    airbnbRate: 329,
    airbnbUrl: "https://www.airbnb.com/rooms/1414909835861328832?guests=1&adults=1&s=67&unique_share_id=a7f30cc1-65c6-4bbb-86d7-02ed3416e341",
    rating: 5.0, reviews: 5, guestFavorite: true,
    heroPlaceholder: "Sunlit living room with rooftop deck access",
    heroImage: "/img/topfloor/11.jpg",
    shortDesc: "The whole 4-level townhouse to yourself. Bedrooms on two floors for privacy, a full kitchen, laundry, A/C, and the rooftop deck. Perfect for families or friends traveling together.",
    perfectFor: "Families · Groups · Long stays",
    longDesc: "Newly built 2023 townhome (~1,200 sqft) one block from Market St. Bedrooms on both first and third floors for privacy. Full kitchen on second floor, laundry on third. Rooftop deck with sunset and Olympic Mountain views. Pets allowed. 15-minute bus ride to UW or downtown Seattle.",
    photos: [
      { src: "/img/topfloor/11.jpg", label: "Townhouse front" },
      { src: "/img/topfloor/01.jpg", label: "Master bedroom" },
      { src: "/img/topfloor/02.jpg", label: "Second bedroom" },
      { src: "/img/topfloor/03.jpg", label: "Third bedroom" },
      { src: "/img/topfloor/04.jpg", label: "Rooftop deck" },
      { src: "/img/topfloor/05.jpg", label: "Rooftop deck view" },
      { src: "/img/topfloor/06.jpg", label: "Rooftop deck, sunset" },
      { src: "/img/topfloor/07.jpg", label: "Rooftop deck, Olympic Mountain view" },
      { src: "/img/topfloor/08.jpg", label: "Rooftop deck, seating" },
      { src: "/img/topfloor/09.jpg", label: "Rooftop deck, detail" },
      { src: "/img/topfloor/10.jpg", label: "Dining area" },
      { src: "/img/topfloor/12.jpg", label: "Chef kitchen" },
      { src: "/img/topfloor/13.png", label: "Living room with sofa bed" },
      { src: "/img/topfloor/14.png", label: "Living room, second view" },
      { src: "/img/topfloor/15.jpg", label: "Outside entrance" },
      { src: "/img/topfloor/16.jpg", label: "Bathroom" },
      { src: "/img/topfloor/17.jpg", label: "Second bathroom" },
      { src: "/img/topfloor/18.jpg", label: "Washer/Dryer" },
      { src: "/img/bamboo/01-bedroom-hero.jpg", label: "First-floor bedroom, afternoon light" },
      { src: "/img/bamboo/02-bedroom-queen.jpg", label: "Queen bed with bamboo headboard" },
      { src: "/img/bamboo/03-nightstand-art.jpg", label: "Nightstand detail" },
      { src: "/img/bamboo/04-bathroom-full.jpg", label: "First-floor bathroom" },
      { src: "/img/bamboo/05-bathroom-vanity.jpg", label: "Vanity with quartz countertop" },
      { src: "/img/bamboo/06-desk-window.jpg", label: "Workspace by the window" },
      { src: "/img/bamboo/07-workspace.jpg", label: "Bamboo closet & desk corner" },
      { src: "/img/bamboo/08-townhouse-exterior.jpg", label: "Townhouse exterior" },
      { src: "/img/bamboo/09-sakura-curtain.jpg", label: "Sakura noren entry" },
      { src: "/img/bamboo/10-closet-desk.jpg", label: "Open closet" },
    ],
    amenities: ["Entire home", "Full kitchen", "Wifi", "Dedicated workspace", "TV", "A/C", "Rooftop deck", "Pets allowed", "Washer/Dryer", "Self check-in (keypad)", "Laundry on 3rd floor", "2 private baths"],
  },
];

export const REVIEWS = [
  { name: "Emma R.", date: "April 2026", property: "Sunlit Zen Retreat", rating: 5, text: "Mandy's place is the rare Airbnb that exceeds the photos. The light through the townhouse in the afternoon is unreal, and we lingered over dinner every night." },
  { name: "Daniel K.", date: "March 2026", property: "Ballard Bamboo Indulgence", rating: 5, text: "Quiet, clean, and exactly as described. Walked to coffee, the brewery, and the farmers market all in one morning. Will absolutely rebook." },
  { name: "Priya S.", date: "February 2026", property: "Ballard Top Floor Suite with Private Chef Kitchen", rating: 5, text: "The chef kitchen sealed it. We cooked salmon we picked up at the market and ate by the sakura tree view. Mandy responded in minutes." },
  { name: "Jon & Alice", date: "January 2026", property: "Sunlit Zen Retreat", rating: 5, text: "Came up from Portland with two friends for a long weekend. Everyone had their own space, the kitchen had everything we needed, and the location was perfect for walking to dinner." },
  { name: "Marcus T.", date: "December 2025", property: "Ballard Bamboo Indulgence", rating: 5, text: "Booked a work trip and used the desk daily. The room-darkening shades are a real thing, and I slept like I was underground." },
  { name: "Sofia L.", date: "November 2025", property: "Ballard Top Floor Suite with Private Chef Kitchen", rating: 5, text: "Felt like staying with a friend who happens to have incredible taste. The townhouse is beautifully minimal and the neighborhood is a dream." },
];

export const NEIGHBORHOOD = [
  { name: "Ballard Sunday Farmers Market", dist: "3 min drive", type: "Market", lat: 47.66805, lng: -122.38444 },
  { name: "Golden Gardens Park", dist: "10 min drive", type: "Beach", lat: 47.69185, lng: -122.40288 },
  { name: "Discovery Park", dist: "14 min drive", type: "Park", lat: 47.65848, lng: -122.41068 },
  { name: "Pike Place Market", dist: "15 min drive", type: "Landmark", lat: 47.60877, lng: -122.34037 },
  { name: "Space Needle", dist: "15 min drive", type: "Landmark", lat: 47.62050, lng: -122.34928 },
  { name: "Fremont", dist: "5 min drive", type: "Neighborhood", lat: 47.65120, lng: -122.35073 },
  { name: "University of Washington", dist: "15 min drive", type: "Campus", lat: 47.65553, lng: -122.30350 },
];
